#pragma once
#include <vector>
#include <random>
#include <algorithm>
#include <chrono>
#include <limits>
#include <iterator>
#include <fstream>
#include <sstream>
#include <omp.h>
#include <initializer_list>
#include <iostream>
#include <cctype>
#include <string>
#include <exception>
#include <stdexcept>
#include <functional>
#include <list>
#include <stdlib.h>
#include <map>
#include <cmath>
#include <cstdarg>